-- 001_init.sql
-- Tabla para control de migraciones

CREATE TABLE IF NOT EXISTS KS_MIGRACIONES (
  MG_IDMIGRACION_PK INT AUTO_INCREMENT PRIMARY KEY,
  MG_NOMBRE VARCHAR(255) NOT NULL,
  MG_FECHA_EJECUCION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
