-- 002_create_core_tables.sql
-- Tablas base: Roles, Sucursales y Trabajadores

CREATE TABLE KS_ROLES (
  RL_IDROL_PK INT AUTO_INCREMENT PRIMARY KEY,
  RL_NOMBRE VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE KS_SUCURSALES (
  SC_IDSUCURSAL_PK INT AUTO_INCREMENT PRIMARY KEY,
  SC_NOMBRE VARCHAR(100) NOT NULL,
  SC_DIRECCION VARCHAR(255)
);

CREATE TABLE KS_TRABAJADORES (
  TR_IDTRABAJADOR_PK INT AUTO_INCREMENT PRIMARY KEY,
  TR_NOMBRE VARCHAR(255) NOT NULL,
  TR_TELEFONO VARCHAR(20),
  TR_PASSWORD VARCHAR(255),
  TR_ACTIVO BOOLEAN DEFAULT TRUE,
  
  RL_IDROL_FK INT NOT NULL,
  SC_IDSUCURSAL_FK INT,

  CONSTRAINT FK_TRABAJADOR_ROL
    FOREIGN KEY (RL_IDROL_FK)
    REFERENCES KS_ROLES(RL_IDROL_PK),
  
  CONSTRAINT FK_TRABAJADOR_SUCURSAL
    FOREIGN KEY (SC_IDSUCURSAL_FK)
    REFERENCES KS_SUCURSALES(SC_IDSUCURSAL_PK)
);
