-- 003_create_business_tables.sql
-- Tablas de negocio: Servicios, Productos y Facturación

CREATE TABLE KS_SERVICIOS (
  SV_IDSERVICIO_PK INT AUTO_INCREMENT PRIMARY KEY,
  SV_NOMBRE VARCHAR(255) NOT NULL,
  SV_ACTIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE KS_PRODUCTOS (
  PR_IDPRODUCTO_PK INT AUTO_INCREMENT PRIMARY KEY,
  PR_NOMBRE VARCHAR(255) NOT NULL,
  PR_ACTIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE KS_FACTURAS (
  FC_IDFACTURA_PK INT AUTO_INCREMENT PRIMARY KEY,
  FC_NUMERO_FACTURA VARCHAR(50) NOT NULL UNIQUE,
  FC_FECHA DATETIME NOT NULL,
  FC_CLIENTE_NOMBRE VARCHAR(255),
  FC_CLIENTE_TELEFONO VARCHAR(20),
  FC_TOTAL DECIMAL(15, 2) DEFAULT 0,
  FC_ESTADO ENUM('PENDIENTE', 'PAGADO', 'CANCELADO') DEFAULT 'PENDIENTE',
  
  SC_IDSUCURSAL_FK INT NOT NULL,
  TR_IDCAJERO_FK INT NOT NULL,

  CONSTRAINT FK_FACTURA_SUCURSAL
    FOREIGN KEY (SC_IDSUCURSAL_FK)
    REFERENCES KS_SUCURSALES(SC_IDSUCURSAL_PK),
  
  CONSTRAINT FK_FACTURA_CAJERO
    FOREIGN KEY (TR_IDCAJERO_FK)
    REFERENCES KS_TRABAJADORES(TR_IDTRABAJADOR_PK)
);

CREATE TABLE KS_FACTURA_DETALLES (
  FD_IDDETALLE_PK INT AUTO_INCREMENT PRIMARY KEY,
  FD_VALOR DECIMAL(15, 2) NOT NULL,
  
  FC_IDFACTURA_FK INT NOT NULL,
  SV_IDSERVICIO_FK INT NOT NULL,
  TR_IDTECNICO_FK INT NOT NULL,

  CONSTRAINT FK_DETALLE_FACTURA
    FOREIGN KEY (FC_IDFACTURA_FK)
    REFERENCES KS_FACTURAS(FC_IDFACTURA_PK),
  
  CONSTRAINT FK_DETALLE_SERVICIO
    FOREIGN KEY (SV_IDSERVICIO_FK)
    REFERENCES KS_SERVICIOS(SV_IDSERVICIO_PK),
  
  CONSTRAINT FK_DETALLE_TECNICO
    FOREIGN KEY (TR_IDTECNICO_FK)
    REFERENCES KS_TRABAJADORES(TR_IDTRABAJADOR_PK)
);

CREATE TABLE KS_FACTURA_PRODUCTOS (
  FP_IDFACTURA_PRODUCTO_PK INT AUTO_INCREMENT PRIMARY KEY,
  FP_VALOR DECIMAL(15, 2) NOT NULL,
  
  FC_IDFACTURA_FK INT NOT NULL,
  PR_IDPRODUCTO_FK INT NOT NULL,
  TR_IDTECNICO_FK INT NOT NULL,

  CONSTRAINT FK_FACTURA_PRODUCTO_FACTURA
    FOREIGN KEY (FC_IDFACTURA_FK)
    REFERENCES KS_FACTURAS(FC_IDFACTURA_PK),
  
  CONSTRAINT FK_FACTURA_PRODUCTO_PRODUCTO
    FOREIGN KEY (PR_IDPRODUCTO_FK)
    REFERENCES KS_PRODUCTOS(PR_IDPRODUCTO_PK),
  
  CONSTRAINT FK_FACTURA_PRODUCTO_TECNICO
    FOREIGN KEY (TR_IDTECNICO_FK)
    REFERENCES KS_TRABAJADORES(TR_IDTRABAJADOR_PK)
);
