-- 004_create_financial_tables.sql
-- Tablas financieras: Métodos de Pago, Pagos, Vales, Gastos y Créditos

CREATE TABLE KS_METODOS_PAGO (
  MP_IDMETODO_PK INT AUTO_INCREMENT PRIMARY KEY,
  MP_NOMBRE VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE KS_PAGOS_FACTURA (
  PF_IDPAGO_PK INT AUTO_INCREMENT PRIMARY KEY,
  PF_VALOR DECIMAL(15, 2) NOT NULL,
  PF_EVIDENCIA_URL VARCHAR(255),
  
  FC_IDFACTURA_FK INT NOT NULL,
  MP_IDMETODO_FK INT NOT NULL,

  CONSTRAINT FK_PAGO_FACTURA
    FOREIGN KEY (FC_IDFACTURA_FK)
    REFERENCES KS_FACTURAS(FC_IDFACTURA_PK),
  
  CONSTRAINT FK_PAGO_METODO
    FOREIGN KEY (MP_IDMETODO_FK)
    REFERENCES KS_METODOS_PAGO(MP_IDMETODO_PK)
);

CREATE TABLE KS_VALES (
  VL_IDVALE_PK INT AUTO_INCREMENT PRIMARY KEY,
  VL_VALOR_TOTAL DECIMAL(15, 2) NOT NULL,
  VL_NUMERO_CUOTAS INT NOT NULL,
  VL_VALOR_CUOTA DECIMAL(15, 2) NOT NULL,
  VL_ESTADO ENUM('PENDIENTE', 'PAGADO', 'CANCELADO') DEFAULT 'PENDIENTE',
  VL_FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  FC_IDFACTURA_FK INT NOT NULL,
  TR_IDTRABAJADOR_FK INT NOT NULL,

  CONSTRAINT FK_VALE_FACTURA
    FOREIGN KEY (FC_IDFACTURA_FK)
    REFERENCES KS_FACTURAS(FC_IDFACTURA_PK),
  
  CONSTRAINT FK_VALE_TRABAJADOR
    FOREIGN KEY (TR_IDTRABAJADOR_FK)
    REFERENCES KS_TRABAJADORES(TR_IDTRABAJADOR_PK)
);

CREATE TABLE KS_GASTOS (
  GS_IDGASTO_PK INT AUTO_INCREMENT PRIMARY KEY,
  GS_CONCEPTO VARCHAR(255) NOT NULL,
  GS_FECHA DATETIME NOT NULL,
  GS_VALOR DECIMAL(15, 2) NOT NULL,
  
  SC_IDSUCURSAL_FK INT,

  CONSTRAINT FK_GASTO_SUCURSAL
    FOREIGN KEY (SC_IDSUCURSAL_FK)
    REFERENCES KS_SUCURSALES(SC_IDSUCURSAL_PK)
);

CREATE TABLE KS_CREDITOS (
  CR_IDCREDITO_PK INT AUTO_INCREMENT PRIMARY KEY,
  CR_VALOR_PENDIENTE DECIMAL(15, 2) NOT NULL,
  CR_FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  FC_IDFACTURA_FK INT NOT NULL,

  CONSTRAINT FK_CREDITO_FACTURA
    FOREIGN KEY (FC_IDFACTURA_FK)
    REFERENCES KS_FACTURAS(FC_IDFACTURA_PK)
);
