-- 005_create_operations_tables.sql
-- Tablas de operación: Solicitudes de Productos

CREATE TABLE KS_SOLICITUDES_PRODUCTOS (
  SP_IDSOLICITUD_PK INT AUTO_INCREMENT PRIMARY KEY,
  SP_CANTIDAD INT NOT NULL,
  SP_ESTADO ENUM('SOLICITADO', 'ENTREGADO') DEFAULT 'SOLICITADO',
  SP_FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  SC_IDSUCURSAL_FK INT NOT NULL,
  PR_IDPRODUCTO_FK INT NOT NULL,

  CONSTRAINT FK_SOLICITUD_SUCURSAL
    FOREIGN KEY (SC_IDSUCURSAL_FK)
    REFERENCES KS_SUCURSALES(SC_IDSUCURSAL_PK),
  
  CONSTRAINT FK_SOLICITUD_PRODUCTO
    FOREIGN KEY (PR_IDPRODUCTO_FK)
    REFERENCES KS_PRODUCTOS(PR_IDPRODUCTO_PK)
);
