-- 006_add_prices_to_catalog.sql
-- Añadir columnas de precio a servicios y productos

ALTER TABLE KS_SERVICIOS 
ADD COLUMN SV_PRECIO DECIMAL(15, 2) DEFAULT 0 AFTER SV_NOMBRE;

ALTER TABLE KS_PRODUCTOS 
ADD COLUMN PR_PRECIO DECIMAL(15, 2) DEFAULT 0 AFTER PR_NOMBRE;
