-- 007_seed_initial_data.sql
-- Datos iniciales: Roles, Métodos de Pago, Sucursal Default y Admin

INSERT IGNORE INTO KS_ROLES (RL_NOMBRE) VALUES ('ADMINISTRADOR_TOTAL'), ('ADMINISTRADOR_PUNTO'), ('TECNICO');

INSERT IGNORE INTO KS_METODOS_PAGO (MP_NOMBRE) VALUES ('TRANSFERENCIA'), ('EFECTIVO'), ('DATAFONO'), ('CREDITO'), ('VALE');

INSERT IGNORE INTO KS_SUCURSALES (SC_NOMBRE, SC_DIRECCION) VALUES ('SUCURSAL CENTRAL', 'Calle Principal #123');

-- Insertar un trabajador administrador por defecto (password: 'admin123')
INSERT IGNORE INTO KS_TRABAJADORES (TR_NOMBRE, TR_TELEFONO, TR_PASSWORD, RL_IDROL_FK, SC_IDSUCURSAL_FK) 
SELECT 'admin', '0000000000', 'admin123', RL_IDROL_PK, SC_IDSUCURSAL_PK 
FROM KS_ROLES, KS_SUCURSALES 
WHERE RL_NOMBRE = 'ADMINISTRADOR_TOTAL' AND SC_NOMBRE = 'SUCURSAL CENTRAL';

INSERT IGNORE INTO KS_TRABAJADORES (TR_NOMBRE, TR_TELEFONO, TR_PASSWORD, RL_IDROL_FK, SC_IDSUCURSAL_FK) 
SELECT 'admin2', '0000000001', 'admin123', RL_IDROL_PK, SC_IDSUCURSAL_PK 
FROM KS_ROLES, KS_SUCURSALES 
WHERE RL_NOMBRE = 'ADMINISTRADOR_TOTAL' AND SC_NOMBRE = 'SUCURSAL CENTRAL';
