-- 008_create_clients_table.sql
-- Tabla para seguimiento dinámico de clientes

CREATE TABLE KS_CLIENTES (
  CL_IDCLIENTE_PK INT AUTO_INCREMENT PRIMARY KEY,
  CL_NOMBRE VARCHAR(255),
  CL_TELEFONO VARCHAR(20) NOT NULL UNIQUE,
  CL_DEUDA_TOTAL DECIMAL(15, 2) DEFAULT 0,
  CL_FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CL_ULTIMA_VISITA TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Agregar FK opcional a facturas para mejor integridad futura
ALTER TABLE KS_FACTURAS 
ADD COLUMN CL_IDCLIENTE_FK INT,
ADD CONSTRAINT FK_FACTURA_CLIENTE 
  FOREIGN KEY (CL_IDCLIENTE_FK) 
  REFERENCES KS_CLIENTES(CL_IDCLIENTE_PK);
