-- 010_add_technician_client_fields.sql
-- Agregar campos para identificar si el cliente es un técnico y manejo de vales

ALTER TABLE KS_FACTURAS 
ADD COLUMN FC_TIPO_CLIENTE ENUM('CLIENTE', 'TECNICO') DEFAULT 'CLIENTE',
ADD COLUMN TR_IDCLIENTE_FK INT NULL;

ALTER TABLE KS_FACTURAS
ADD CONSTRAINT FK_FACTURA_CLIENTE_TECNICO 
FOREIGN KEY (TR_IDCLIENTE_FK) REFERENCES KS_TRABAJADORES(TR_IDTRABAJADOR_PK);
