-- 014_create_credit_abonos.sql
-- Tabla para registrar el historial de abonos a créditos (Trazabilidad)

CREATE TABLE IF NOT EXISTS KS_CREDITO_ABONOS (
  AB_IDABONO_PK INT AUTO_INCREMENT PRIMARY KEY,
  AB_VALOR DECIMAL(15, 2) NOT NULL,
  AB_FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  CR_IDCREDITO_FK INT NOT NULL,
  
  CONSTRAINT FK_ABONO_CREDITO
    FOREIGN KEY (CR_IDCREDITO_FK)
    REFERENCES KS_CREDITOS(CR_IDCREDITO_PK)
);
