-- 015_add_evidence_to_abonos.sql
-- Agregar campo de evidencia y mejorar campo de fecha en KS_CREDITO_ABONOS

ALTER TABLE KS_CREDITO_ABONOS 
ADD COLUMN AB_EVIDENCIA_URL VARCHAR(255) NULL AFTER AB_VALOR,
MODIFY COLUMN AB_FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
