-- 016_associate_products_with_services.sql
-- Permite asociar un producto con un servicio específico dentro de una factura

ALTER TABLE KS_FACTURA_PRODUCTOS
ADD COLUMN FD_IDDETALLE_FK INT NULL AFTER PR_IDPRODUCTO_FK,
ADD CONSTRAINT FK_FACTURA_PRODUCTO_DETALLE
  FOREIGN KEY (FD_IDDETALLE_FK)
  REFERENCES KS_FACTURA_DETALLES(FD_IDDETALLE_PK)
  ON DELETE SET NULL;
