-- 018_rename_vales_to_servicios_trabajador.sql
-- Migración para renombrar "Vales" a "Servicios de Trabajador" de forma compatible con MySQL 5.7

SET FOREIGN_KEY_CHECKS=0;

-- 1. Actualizar el método de pago
UPDATE KS_METODOS_PAGO 
SET MP_NOMBRE = 'SERVICIO DE TRABAJADOR' 
WHERE MP_NOMBRE = 'VALE';

-- 2. Renombrar tablas principales (COMENTADO: Ya se ejecutó en intento anterior antes del error de sintaxis)
-- RENAME TABLE KS_VALES TO KS_SERVICIOS_TRABAJADOR;
-- RENAME TABLE KS_VALE_CUOTAS TO KS_SERVICIO_TRABAJADOR_CUOTAS;

-- 3. Renombrar columnas en KS_SERVICIOS_TRABAJADOR (usando CHANGE para compatibilidad)
ALTER TABLE KS_SERVICIOS_TRABAJADOR
  CHANGE VL_IDVALE_PK ST_IDSERVICIO_TRABAJADOR_PK INT AUTO_INCREMENT,
  CHANGE VL_VALOR_TOTAL ST_VALOR_TOTAL DECIMAL(15, 2) NOT NULL,
  CHANGE VL_NUMERO_CUOTAS ST_NUMERO_CUOTAS INT NOT NULL,
  CHANGE VL_VALOR_CUOTA ST_VALOR_CUOTA DECIMAL(15, 2) NOT NULL,
  CHANGE VL_ESTADO ST_ESTADO ENUM('PENDIENTE', 'PAGADO', 'CANCELADO') DEFAULT 'PENDIENTE',
  CHANGE VL_FECHA ST_FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CHANGE VL_FECHA_INICIO_COBRO ST_FECHA_INICIO_COBRO DATE NULL;

-- 4. Renombrar columnas en KS_SERVICIO_TRABAJADOR_CUOTAS
ALTER TABLE KS_SERVICIO_TRABAJADOR_CUOTAS
  CHANGE VC_IDCUOTA_PK STC_IDCUOTA_PK INT AUTO_INCREMENT,
  CHANGE VC_NUMERO_CUOTA STC_NUMERO_CUOTA INT NOT NULL,
  CHANGE VC_VALOR_CUOTA STC_VALOR_CUOTA DECIMAL(15, 2) NOT NULL,
  CHANGE VC_ESTADO STC_ESTADO ENUM('PENDIENTE', 'PAGADO', 'CANCELADO') DEFAULT 'PENDIENTE',
  CHANGE VC_FECHA_COBRO STC_FECHA_COBRO DATE NOT NULL,
  CHANGE VL_IDVALE_FK ST_IDSERVICIO_TRABAJADOR_FK INT NOT NULL;

-- 5. Renombrar columnas en Otras tablas
ALTER TABLE KS_NOMINA_DETALLES
  CHANGE ND_DEDUCCIONES_VALES ND_DEDUCCIONES_SERVICIOS_TRABAJADOR DECIMAL(15, 2) DEFAULT 0;

-- 6. Opcional: renombrar los índices temporalmente puede causar fallos de sintaxis en 5.7 si usamos RENAME INDEX. 
-- Para mayor seguridad, hacemos DROP INDEX y volvemos a crearlo.
DROP INDEX IDX_VALE_CUOTA_ESTADO ON KS_SERVICIO_TRABAJADOR_CUOTAS;
DROP INDEX IDX_VALE_CUOTA_FECHA ON KS_SERVICIO_TRABAJADOR_CUOTAS;

CREATE INDEX IDX_ST_CUOTA_ESTADO ON KS_SERVICIO_TRABAJADOR_CUOTAS(STC_ESTADO);
CREATE INDEX IDX_ST_CUOTA_FECHA ON KS_SERVICIO_TRABAJADOR_CUOTAS(STC_FECHA_COBRO);

SET FOREIGN_KEY_CHECKS=1;
