-- 019_create_adelantos_table.sql
-- Creación de la tabla de adelantos de nómina para los trabajadores

CREATE TABLE KS_ADELANTOS (
  AD_IDADELANTO_PK INT AUTO_INCREMENT PRIMARY KEY,
  TR_IDTRABAJADOR_FK INT NOT NULL,
  AD_MONTO DECIMAL(15, 2) NOT NULL,
  AD_FECHA DATE NOT NULL,
  AD_ESTADO ENUM('PENDIENTE', 'DESCONTADO', 'ANULADO') DEFAULT 'PENDIENTE',
  NM_IDNOMINA_FK INT NULL, -- Se llena cuando la nómina descuenta el adelanto
  AD_OBSERVACIONES TEXT NULL,
  AD_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT FK_ADELANTO_TRABAJADOR
    FOREIGN KEY (TR_IDTRABAJADOR_FK)
    REFERENCES KS_TRABAJADORES(TR_IDTRABAJADOR_PK)
    ON DELETE CASCADE,
    
  CONSTRAINT FK_ADELANTO_NOMINA
    FOREIGN KEY (NM_IDNOMINA_FK)
    REFERENCES KS_NOMINAS(NM_IDNOMINA_PK)
    ON DELETE SET NULL
);

-- Índices para mejorar las consultas de adelantos pendientes por trabajador
CREATE INDEX IDX_ADELANTO_TRABAJADOR ON KS_ADELANTOS(TR_IDTRABAJADOR_FK);
CREATE INDEX IDX_ADELANTO_ESTADO ON KS_ADELANTOS(AD_ESTADO);
