-- 026_alter_solicitudes_productos.sql
-- Ajustar tabla de solicitudes de productos para incluir trabajador y fechas extendidas

-- Primero, actualizamos el estado actual si existe
UPDATE KS_SOLICITUDES_PRODUCTOS SET SP_ESTADO = 'PENDIENTE' WHERE SP_ESTADO = 'SOLICITADO';

ALTER TABLE KS_SOLICITUDES_PRODUCTOS 
  MODIFY COLUMN SP_ESTADO ENUM('PENDIENTE', 'ENTREGADO', 'CANCELADO') DEFAULT 'PENDIENTE',
  CHANGE COLUMN SP_FECHA SP_FECHA_SOLICITUD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN TR_IDTRABAJADOR_FK INT NULL AFTER PR_IDPRODUCTO_FK,
  ADD COLUMN SP_FECHA_ENTREGA DATETIME NULL AFTER SP_FECHA_SOLICITUD,
  ADD COLUMN SP_COMENTARIOS TEXT NULL AFTER SP_FECHA_ENTREGA,
  ADD CONSTRAINT FK_SOLICITUD_TRABAJADOR FOREIGN KEY (TR_IDTRABAJADOR_FK) REFERENCES KS_TRABAJADORES(TR_IDTRABAJADOR_PK);
