-- 030_modulate_product_commissions.sql
-- Modulación de comisiones por producto y detalle de nómina

-- 1. Modificar KS_PRODUCTOS para incluir campos de comisión individual
ALTER TABLE KS_PRODUCTOS
ADD COLUMN PR_APLICA_COMISION BOOLEAN DEFAULT FALSE AFTER PR_ACTIVO,
ADD COLUMN PR_PORCENTAJE_COMISION DECIMAL(5, 2) DEFAULT 0.00 AFTER PR_APLICA_COMISION;

-- 2. Modificar KS_NOMINA_CONFIG para eliminar porcentaje global de producto
-- (Ahora la comisión se define por producto)
ALTER TABLE KS_NOMINA_CONFIG
DROP COLUMN NC_PORCENTAJE_PRODUCTO;

-- 3. Modificar KS_FACTURA_PRODUCTOS para persistir la comisión y soportar cantidades
ALTER TABLE KS_FACTURA_PRODUCTOS
ADD COLUMN FP_CANTIDAD INT DEFAULT 1 AFTER FP_VALOR,
ADD COLUMN FP_PORCENTAJE_APLICADO DECIMAL(5, 2) DEFAULT 0.00 AFTER PR_IDPRODUCTO_FK,
ADD COLUMN FP_COMISION_VALOR DECIMAL(15, 2) DEFAULT 0.00 AFTER FP_PORCENTAJE_APLICADO;

-- 4. Modificar KS_FACTURA_DETALLES para incluir cantidad (para desglose en nómina)
ALTER TABLE KS_FACTURA_DETALLES
ADD COLUMN FD_CANTIDAD INT DEFAULT 1 AFTER FD_VALOR;
