-- 001_test_data.sql
-- Datos de prueba masivos y continuos (30 días sin huecos)
-- Genera un historial real día tras día para técnicos y administradores.

USE kairos_stylos;

-- 1. LIMPIEZA TOTAL
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE KS_PAGOS_FACTURA;
TRUNCATE TABLE KS_FACTURA_DETALLES;
TRUNCATE TABLE KS_FACTURA_PRODUCTOS;
TRUNCATE TABLE KS_FACTURAS;
TRUNCATE TABLE KS_SERVICIO_TRABAJADOR_CUOTAS;
TRUNCATE TABLE KS_SERVICIOS_TRABAJADOR;
TRUNCATE TABLE KS_ADELANTOS;
TRUNCATE TABLE KS_GASTOS;
TRUNCATE TABLE KS_NOMINA_DETALLES;
TRUNCATE TABLE KS_NOMINAS;
TRUNCATE TABLE KS_CREDITO_ABONOS;
TRUNCATE TABLE KS_CREDITOS;
DELETE FROM KS_TRABAJADORES WHERE RL_IDROL_FK IN (SELECT RL_IDROL_PK FROM KS_ROLES WHERE RL_NOMBRE IN ('TECNICO', 'ADMINISTRADOR_PUNTO'));
SET FOREIGN_KEY_CHECKS = 1;

-- 2. CATALOGOS BASE (Asegurar que existan los servicios y productos)
INSERT IGNORE INTO KS_SERVICIOS (SV_NOMBRE, SV_ACTIVO) VALUES 
('CORTE Y BARBA COMBO', TRUE), ('BARBA SPA', TRUE), ('MANICURE', TRUE), ('LIMPIEZA FACIAL', TRUE), ('KERATINA', TRUE);

INSERT IGNORE INTO KS_PRODUCTOS (PR_NOMBRE, PR_ACTIVO) VALUES 
('POMADA MATE', TRUE), ('MINOXIDIL', TRUE), ('SHAMPOO', TRUE), ('CEPILLO BARBA', TRUE);

INSERT IGNORE INTO KS_SUCURSALES (SC_NOMBRE, SC_DIRECCION) 
SELECT 'SUCURSAL NORTE', 'Av. Sexta #10-20' FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM KS_SUCURSALES WHERE SC_NOMBRE = 'SUCURSAL NORTE');

-- 3. PERSONAL
SET @rol_tecnico = (SELECT RL_IDROL_PK FROM KS_ROLES WHERE RL_NOMBRE = 'TECNICO' LIMIT 1);
SET @rol_admin = (SELECT RL_IDROL_PK FROM KS_ROLES WHERE RL_NOMBRE = 'ADMINISTRADOR_PUNTO' LIMIT 1);
SET @sc_central = (SELECT SC_IDSUCURSAL_PK FROM KS_SUCURSALES WHERE SC_NOMBRE = 'SUCURSAL CENTRAL' LIMIT 1);
SET @sc_norte = (SELECT SC_IDSUCURSAL_PK FROM KS_SUCURSALES WHERE SC_NOMBRE = 'SUCURSAL NORTE' LIMIT 1);

INSERT INTO KS_TRABAJADORES (TR_NOMBRE, TR_TELEFONO, TR_PASSWORD, RL_IDROL_FK, SC_IDSUCURSAL_FK, TR_ACTIVO) VALUES 
('Ricardo Admin Central', '3109990001', '123', @rol_admin, @sc_central, TRUE),
('Claudia Admin Norte', '3109990002', '123', @rol_admin, @sc_norte, TRUE),
('Juan Barbero', '3001112233', '123', @rol_tecnico, @sc_central, TRUE),
('Maria Estilista', '3114445566', '123', @rol_tecnico, @sc_central, TRUE),
('Pedro Master', '3227778899', '123', @rol_tecnico, @sc_norte, TRUE);

SET @juan = (SELECT TR_IDTRABAJADOR_PK FROM KS_TRABAJADORES WHERE TR_NOMBRE = 'Juan Barbero');
SET @maria = (SELECT TR_IDTRABAJADOR_PK FROM KS_TRABAJADORES WHERE TR_NOMBRE = 'Maria Estilista');
SET @pedro = (SELECT TR_IDTRABAJADOR_PK FROM KS_TRABAJADORES WHERE TR_NOMBRE = 'Pedro Master');
SET @admin_c = (SELECT TR_IDTRABAJADOR_PK FROM KS_TRABAJADORES WHERE TR_NOMBRE = 'Ricardo Admin Central');
SET @admin_n = (SELECT TR_IDTRABAJADOR_PK FROM KS_TRABAJADORES WHERE TR_NOMBRE = 'Claudia Admin Norte');

-- IDs de utilitarios
SET @sv_corte = (SELECT SV_IDSERVICIO_PK FROM KS_SERVICIOS WHERE SV_NOMBRE = 'CORTE Y BARBA COMBO' LIMIT 1);
SET @sv_manic = (SELECT SV_IDSERVICIO_PK FROM KS_SERVICIOS WHERE SV_NOMBRE = 'MANICURE' LIMIT 1);
SET @pr_shamp = (SELECT PR_IDPRODUCTO_PK FROM KS_PRODUCTOS WHERE PR_NOMBRE = 'SHAMPOO' LIMIT 1);
SET @mp_efec = (SELECT MP_IDMETODO_PK FROM KS_METODOS_PAGO WHERE MP_NOMBRE = 'EFECTIVO' LIMIT 1);

-- 4. GENERACIÓN DE FACTURAS DÍA TRAS DÍA (Últimos 28 días)
-- (Usamos una técnica de repetición manual inteligente para cubrir todos los días)

-- PROCEDIMIENTO PARA NO DEPENDER DE VARIABLES SI ES POSIBLE EN UN SCRIPT
-- SEMANA 4 (Hace 28-21 días)
INSERT INTO KS_FACTURAS (FC_NUMERO_FACTURA, FC_FECHA, FC_CLIENTE_NOMBRE, FC_TOTAL, FC_ESTADO, SC_IDSUCURSAL_FK, TR_IDCAJERO_FK) VALUES
(10001, DATE_SUB(CURRENT_DATE(), INTERVAL 28 DAY), 'C-28-1', 50000, 'PAGADO', @sc_central, @admin_c),
(10002, DATE_SUB(CURRENT_DATE(), INTERVAL 28 DAY), 'C-28-2', 25000, 'PAGADO', @sc_norte, @admin_n),
(10003, DATE_SUB(CURRENT_DATE(), INTERVAL 27 DAY), 'C-27-1', 40000, 'PAGADO', @sc_central, @admin_c),
(10004, DATE_SUB(CURRENT_DATE(), INTERVAL 27 DAY), 'C-27-2', 60000, 'PAGADO', @sc_norte, @admin_n),
(10005, DATE_SUB(CURRENT_DATE(), INTERVAL 26 DAY), 'C-26-1', 30000, 'PAGADO', @sc_central, @admin_c),
(10006, DATE_SUB(CURRENT_DATE(), INTERVAL 26 DAY), 'C-26-2', 45000, 'PAGADO', @sc_norte, @admin_n),
(10007, DATE_SUB(CURRENT_DATE(), INTERVAL 25 DAY), 'C-25-1', 20000, 'PAGADO', @sc_central, @admin_c),
(10008, DATE_SUB(CURRENT_DATE(), INTERVAL 25 DAY), 'C-25-2', 55000, 'PAGADO', @sc_norte, @admin_n),
(10009, DATE_SUB(CURRENT_DATE(), INTERVAL 24 DAY), 'C-24-1', 35000, 'PAGADO', @sc_central, @admin_c),
(10010, DATE_SUB(CURRENT_DATE(), INTERVAL 24 DAY), 'C-24-2', 15000, 'PAGADO', @sc_norte, @admin_n),
(10011, DATE_SUB(CURRENT_DATE(), INTERVAL 23 DAY), 'C-23-1', 50000, 'PAGADO', @sc_central, @admin_c),
(10012, DATE_SUB(CURRENT_DATE(), INTERVAL 23 DAY), 'C-23-2', 20000, 'PAGADO', @sc_norte, @admin_n),
(10013, DATE_SUB(CURRENT_DATE(), INTERVAL 22 DAY), 'C-22-1', 45000, 'PAGADO', @sc_central, @admin_c),
(10014, DATE_SUB(CURRENT_DATE(), INTERVAL 22 DAY), 'C-22-2', 30000, 'PAGADO', @sc_norte, @admin_n),
(10015, DATE_SUB(CURRENT_DATE(), INTERVAL 21 DAY), 'C-21-1', 60000, 'PAGADO', @sc_central, @admin_c);

-- Relacionar facturas de semana 4 con técnicos
INSERT INTO KS_FACTURA_DETALLES (FD_VALOR, FC_IDFACTURA_FK, SV_IDSERVICIO_FK, TR_IDTECNICO_FK)
SELECT 20000, FC_IDFACTURA_PK, @sv_corte, @juan FROM KS_FACTURAS WHERE FC_NUMERO_FACTURA IN (10001,10003,10005,10007,10009,10011,10013,10015);
INSERT INTO KS_FACTURA_DETALLES (FD_VALOR, FC_IDFACTURA_FK, SV_IDSERVICIO_FK, TR_IDTECNICO_FK)
SELECT 25000, FC_IDFACTURA_PK, @sv_manic, @maria FROM KS_FACTURAS WHERE FC_NUMERO_FACTURA IN (10002,10004,10006,10008,10010,10012,10014);
INSERT INTO KS_PAGOS_FACTURA (PF_VALOR, FC_IDFACTURA_FK, MP_IDMETODO_FK)
SELECT FC_TOTAL, FC_IDFACTURA_PK, @mp_efec FROM KS_FACTURAS WHERE FC_NUMERO_FACTURA BETWEEN 10001 AND 10015;

-- SEMANA 3 (Hace 20-14 días)
INSERT INTO KS_FACTURAS (FC_NUMERO_FACTURA, FC_FECHA, FC_CLIENTE_NOMBRE, FC_TOTAL, FC_ESTADO, SC_IDSUCURSAL_FK, TR_IDCAJERO_FK) VALUES
(20001, DATE_SUB(CURRENT_DATE(), INTERVAL 20 DAY), 'C-20-1', 35000, 'PAGADO', @sc_central, @admin_c),
(20002, DATE_SUB(CURRENT_DATE(), INTERVAL 20 DAY), 'C-20-2', 40000, 'PAGADO', @sc_norte, @admin_n),
(20003, DATE_SUB(CURRENT_DATE(), INTERVAL 19 DAY), 'C-19-1', 25000, 'PAGADO', @sc_central, @admin_c),
(20004, DATE_SUB(CURRENT_DATE(), INTERVAL 19 DAY), 'C-19-2', 30000, 'PAGADO', @sc_norte, @admin_n),
(20005, DATE_SUB(CURRENT_DATE(), INTERVAL 18 DAY), 'C-18-1', 55000, 'PAGADO', @sc_central, @admin_c),
(20006, DATE_SUB(CURRENT_DATE(), INTERVAL 18 DAY), 'C-18-2', 15000, 'PAGADO', @sc_norte, @admin_n),
(20007, DATE_SUB(CURRENT_DATE(), INTERVAL 17 DAY), 'C-17-1', 40000, 'PAGADO', @sc_central, @admin_c),
(20008, DATE_SUB(CURRENT_DATE(), INTERVAL 17 DAY), 'C-17-2', 65000, 'PAGADO', @sc_norte, @admin_n),
(20009, DATE_SUB(CURRENT_DATE(), INTERVAL 16 DAY), 'C-16-1', 20000, 'PAGADO', @sc_central, @admin_c),
(20010, DATE_SUB(CURRENT_DATE(), INTERVAL 16 DAY), 'C-16-2', 40000, 'PAGADO', @sc_norte, @admin_n),
(20011, DATE_SUB(CURRENT_DATE(), INTERVAL 15 DAY), 'C-15-1', 30000, 'PAGADO', @sc_central, @admin_c),
(20012, DATE_SUB(CURRENT_DATE(), INTERVAL 15 DAY), 'C-15-2', 20000, 'PAGADO', @sc_norte, @admin_n),
(20013, DATE_SUB(CURRENT_DATE(), INTERVAL 14 DAY), 'C-14-1', 50000, 'PAGADO', @sc_central, @admin_c),
(20014, DATE_SUB(CURRENT_DATE(), INTERVAL 14 DAY), 'C-14-2', 70000, 'PAGADO', @sc_norte, @admin_n);

-- Detalles Semana 3
INSERT INTO KS_FACTURA_DETALLES (FD_VALOR, FC_IDFACTURA_FK, SV_IDSERVICIO_FK, TR_IDTECNICO_FK)
SELECT 15000, FC_IDFACTURA_PK, @sv_corte, @juan FROM KS_FACTURAS WHERE FC_NUMERO_FACTURA BETWEEN 20001 AND 20014 AND MOD(FC_IDFACTURA_PK, 2) = 0;
INSERT INTO KS_FACTURA_DETALLES (FD_VALOR, FC_IDFACTURA_FK, SV_IDSERVICIO_FK, TR_IDTECNICO_FK)
SELECT 20000, FC_IDFACTURA_PK, @sv_manic, @pedro FROM KS_FACTURAS WHERE FC_NUMERO_FACTURA BETWEEN 20001 AND 20014 AND MOD(FC_IDFACTURA_PK, 2) <> 0;
INSERT INTO KS_PAGOS_FACTURA (PF_VALOR, FC_IDFACTURA_FK, MP_IDMETODO_FK)
SELECT FC_TOTAL, FC_IDFACTURA_PK, @mp_efec FROM KS_FACTURAS WHERE FC_NUMERO_FACTURA BETWEEN 20001 AND 20014;

-- SEMANA 2 (Hace 13-7 días)
INSERT INTO KS_FACTURAS (FC_NUMERO_FACTURA, FC_FECHA, FC_CLIENTE_NOMBRE, FC_TOTAL, FC_ESTADO, SC_IDSUCURSAL_FK, TR_IDCAJERO_FK) VALUES
(30001, DATE_SUB(CURRENT_DATE(), INTERVAL 13 DAY), 'C-13-1', 40000, 'PAGADO', @sc_central, @admin_c),
(30002, DATE_SUB(CURRENT_DATE(), INTERVAL 12 DAY), 'C-12-1', 40000, 'PAGADO', @sc_central, @admin_c),
(30003, DATE_SUB(CURRENT_DATE(), INTERVAL 11 DAY), 'C-11-1', 40000, 'PAGADO', @sc_central, @admin_c),
(30004, DATE_SUB(CURRENT_DATE(), INTERVAL 10 DAY), 'C-10-1', 40000, 'PAGADO', @sc_central, @admin_c),
(30005, DATE_SUB(CURRENT_DATE(), INTERVAL 9 DAY), 'C-9-1', 40000, 'PAGADO', @sc_central, @admin_c),
(30006, DATE_SUB(CURRENT_DATE(), INTERVAL 8 DAY), 'C-8-1', 40000, 'PAGADO', @sc_central, @admin_c),
(30007, DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY), 'C-7-1', 40000, 'PAGADO', @sc_central, @admin_c);

INSERT INTO KS_FACTURA_DETALLES (FD_VALOR, FC_IDFACTURA_FK, SV_IDSERVICIO_FK, TR_IDTECNICO_FK)
SELECT 40000, FC_IDFACTURA_PK, @sv_corte, @maria FROM KS_FACTURAS WHERE FC_NUMERO_FACTURA BETWEEN 30001 AND 30007;
INSERT INTO KS_PAGOS_FACTURA (PF_VALOR, FC_IDFACTURA_FK, MP_IDMETODO_FK)
SELECT FC_TOTAL, FC_IDFACTURA_PK, @mp_efec FROM KS_FACTURAS WHERE FC_NUMERO_FACTURA BETWEEN 30001 AND 30007;

-- SEMANA 1 (Hace 6-0 días)
INSERT INTO KS_FACTURAS (FC_NUMERO_FACTURA, FC_FECHA, FC_CLIENTE_NOMBRE, FC_TOTAL, FC_ESTADO, SC_IDSUCURSAL_FK, TR_IDCAJERO_FK) VALUES
(40001, DATE_SUB(CURRENT_DATE(), INTERVAL 6 DAY), 'C-6-1', 40000, 'PAGADO', @sc_central, @admin_c),
(40002, DATE_SUB(CURRENT_DATE(), INTERVAL 5 DAY), 'C-5-1', 40000, 'PAGADO', @sc_central, @admin_c),
(40003, DATE_SUB(CURRENT_DATE(), INTERVAL 4 DAY), 'C-4-1', 40000, 'PAGADO', @sc_central, @admin_c),
(40004, DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY), 'C-3-1', 40000, 'PAGADO', @sc_central, @admin_c),
(40005, DATE_SUB(CURRENT_DATE(), INTERVAL 2 DAY), 'C-2-1', 40000, 'PAGADO', @sc_central, @admin_c),
(40006, DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY), 'C-1-1', 40000, 'PAGADO', @sc_central, @admin_c),
(40007, CURRENT_DATE(), 'C-Hoy-1', 40000, 'PAGADO', @sc_central, @admin_c);

INSERT INTO KS_FACTURA_DETALLES (FD_VALOR, FC_IDFACTURA_FK, SV_IDSERVICIO_FK, TR_IDTECNICO_FK)
SELECT 40000, FC_IDFACTURA_PK, @sv_corte, @juan FROM KS_FACTURAS WHERE FC_NUMERO_FACTURA BETWEEN 40001 AND 40007;
INSERT INTO KS_PAGOS_FACTURA (PF_VALOR, FC_IDFACTURA_FK, MP_IDMETODO_FK)
SELECT FC_TOTAL, FC_IDFACTURA_PK, @mp_efec FROM KS_FACTURAS WHERE FC_NUMERO_FACTURA BETWEEN 40001 AND 40007;

-- 5. VALES Y ADELANTOS (Variaciones de deudas)
INSERT INTO KS_ADELANTOS (AD_MONTO, AD_OBSERVACIONES, AD_FECHA, AD_ESTADO, TR_IDTRABAJADOR_FK, AD_CUOTAS, AD_CUOTAS_PAGADAS, AD_FECHA_INICIO_COBRO) 
VALUES (50000, 'Vale 1 Juan', DATE_SUB(CURRENT_DATE(), INTERVAL 15 DAY), 'PENDIENTE', @juan, 2, 0, DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY));

-- 6. GASTOS DIARIOS
INSERT INTO KS_GASTOS (GS_CONCEPTO, GS_VALOR, GS_FECHA, SC_IDSUCURSAL_FK) 
VALUES ('Insumos Barberia', 50000, DATE_SUB(CURRENT_DATE(), INTERVAL 20 DAY), @sc_central),
('Servicios Mes', 250000, DATE_SUB(CURRENT_DATE(), INTERVAL 10 DAY), @sc_central),
('Publicidad Redes', 80000, DATE_SUB(CURRENT_DATE(), INTERVAL 5 DAY), @sc_central);

-- ✨ FIN DE SEED CONTINUO ✨