-- 001_test_data.sql
-- Datos de prueba robustos y variados (3 semanas de historial)

USE kyros_stylos;

-- 1. Limpiar datos transaccionales (Manteniendo configuración base y admins)
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE KS_PAGOS_FACTURA;
TRUNCATE TABLE KS_FACTURA_DETALLES;
TRUNCATE TABLE KS_FACTURA_PRODUCTOS;
TRUNCATE TABLE KS_FACTURAS;
TRUNCATE TABLE KS_SERVICIO_TRABAJADOR_CUOTAS;
TRUNCATE TABLE KS_SERVICIOS_TRABAJADOR;
TRUNCATE TABLE KS_ADELANTOS;
TRUNCATE TABLE KS_GASTOS;
TRUNCATE TABLE KS_NOMINA_DETALLES;
TRUNCATE TABLE KS_NOMINAS;
TRUNCATE TABLE KS_SERVICIOS;
TRUNCATE TABLE KS_PRODUCTOS;
TRUNCATE TABLE KS_CREDITO_ABONOS;
TRUNCATE TABLE KS_CREDITOS;
DELETE FROM KS_TRABAJADORES WHERE RL_IDROL_FK IN (SELECT RL_IDROL_PK FROM KS_ROLES WHERE RL_NOMBRE = 'TECNICO');
SET FOREIGN_KEY_CHECKS = 1;

-- 2. Insertar Catálogos (Servicios, Productos, Clientes)
INSERT INTO KS_SERVICIOS (SV_NOMBRE, SV_ACTIVO) VALUES 
('CORTE CABALLERO', TRUE),
('BARBA PROFESIONAL', TRUE),
('MANICURE MASCULINO', TRUE),
('LIMPIEZA FACIAL', TRUE),
('COLOR Y CAMBIO LOOK', TRUE);

INSERT INTO KS_PRODUCTOS (PR_NOMBRE, PR_ACTIVO) VALUES 
('CERA MOLDED PREMIUM', TRUE),
('MINOXIDIL FORTE', TRUE),
('SHAMPOO ANTI-GRASA', TRUE),
('ACEITE BARBA SANDALWOOD', TRUE);

-- (No se insertan clientes previamente, se crean dinámicamente en facturas)
-- (Los números de factura ahora son puramente numéricos, sin prefijos de texto)


-- 3. Insertar Técnicos y capturar sus IDs
INSERT INTO KS_TRABAJADORES (TR_NOMBRE, TR_TELEFONO, TR_PASSWORD, RL_IDROL_FK, SC_IDSUCURSAL_FK) 
SELECT 'Juan Perez', '3001112233', '123456', RL_IDROL_PK, SC_IDSUCURSAL_PK 
FROM KS_ROLES, KS_SUCURSALES WHERE RL_NOMBRE = 'TECNICO' AND SC_NOMBRE = 'SUCURSAL CENTRAL';
SET @juan_id = LAST_INSERT_ID();

INSERT INTO KS_TRABAJADORES (TR_NOMBRE, TR_TELEFONO, TR_PASSWORD, RL_IDROL_FK, SC_IDSUCURSAL_FK) 
SELECT 'Maria Lopez', '3004445566', '123456', RL_IDROL_PK, SC_IDSUCURSAL_PK 
FROM KS_ROLES, KS_SUCURSALES WHERE RL_NOMBRE = 'TECNICO' AND SC_NOMBRE = 'SUCURSAL CENTRAL';
SET @maria_id = LAST_INSERT_ID();

INSERT INTO KS_TRABAJADORES (TR_NOMBRE, TR_TELEFONO, TR_PASSWORD, RL_IDROL_FK, SC_IDSUCURSAL_FK) 
SELECT 'Pedro Gomez', '3007778899', '123456', RL_IDROL_PK, SC_IDSUCURSAL_PK 
FROM KS_ROLES, KS_SUCURSALES WHERE RL_NOMBRE = 'TECNICO' AND SC_NOMBRE = 'SUCURSAL CENTRAL';
SET @pedro_id = LAST_INSERT_ID();

-- Capturar otros IDs comunes
SET @sucursal_id = (SELECT SC_IDSUCURSAL_PK FROM KS_SUCURSALES LIMIT 1);
SET @admin_id = (SELECT TR_IDTRABAJADOR_PK FROM KS_TRABAJADORES ORDER BY RL_IDROL_FK ASC LIMIT 1);
SET @mp_efectivo = (SELECT MP_IDMETODO_PK FROM KS_METODOS_PAGO WHERE MP_NOMBRE = 'EFECTIVO');
SET @mp_transf = (SELECT MP_IDMETODO_PK FROM KS_METODOS_PAGO WHERE MP_NOMBRE = 'TRANSFERENCIA');
SET @mp_datafono = (SELECT MP_IDMETODO_PK FROM KS_METODOS_PAGO WHERE MP_NOMBRE = 'DATAFONO');
SET @sv_corte = (SELECT SV_IDSERVICIO_PK FROM KS_SERVICIOS WHERE SV_NOMBRE = 'CORTE CABALLERO');
SET @sv_barba = (SELECT SV_IDSERVICIO_PK FROM KS_SERVICIOS WHERE SV_NOMBRE = 'BARBA PROFESIONAL');
SET @pr_cera = (SELECT PR_IDPRODUCTO_PK FROM KS_PRODUCTOS WHERE PR_NOMBRE = 'CERA MOLDED PREMIUM');

-- 4. SEMANA 3 (Hace 21 a 15 días)
INSERT INTO KS_FACTURAS (FC_NUMERO_FACTURA, FC_FECHA, FC_CLIENTE_NOMBRE, FC_CLIENTE_TELEFONO, FC_TOTAL, FC_ESTADO, SC_IDSUCURSAL_FK, TR_IDCAJERO_FK)
VALUES ('1001', DATE_SUB(CURRENT_DATE(), INTERVAL 20 DAY), 'Carlos Andres', '3101234567', 40000, 'PAGADO', @sucursal_id, @admin_id);
SET @fc1 = LAST_INSERT_ID();
INSERT INTO KS_FACTURA_DETALLES (FD_VALOR, FC_IDFACTURA_FK, SV_IDSERVICIO_FK, TR_IDTECNICO_FK) VALUES (25000, @fc1, @sv_corte, @juan_id), (15000, @fc1, @sv_barba, @juan_id);
INSERT INTO KS_PAGOS_FACTURA (PF_VALOR, FC_IDFACTURA_FK, MP_IDMETODO_FK) VALUES (40000, @fc1, @mp_efectivo);

INSERT INTO KS_FACTURAS (FC_NUMERO_FACTURA, FC_FECHA, FC_CLIENTE_NOMBRE, FC_CLIENTE_TELEFONO, FC_TOTAL, FC_ESTADO, SC_IDSUCURSAL_FK, TR_IDCAJERO_FK)
VALUES ('1002', DATE_SUB(CURRENT_DATE(), INTERVAL 19 DAY), 'Lucia Mendes', '3119876543', 55000, 'PAGADO', @sucursal_id, @admin_id);
SET @fc2 = LAST_INSERT_ID();
INSERT INTO KS_FACTURA_DETALLES (FD_VALOR, FC_IDFACTURA_FK, SV_IDSERVICIO_FK, TR_IDTECNICO_FK) VALUES (25000, @fc2, @sv_corte, @maria_id);
INSERT INTO KS_FACTURA_PRODUCTOS (FP_VALOR, FC_IDFACTURA_FK, PR_IDPRODUCTO_FK, TR_IDTECNICO_FK) VALUES (30000, @fc2, @pr_cera, @maria_id);
INSERT INTO KS_PAGOS_FACTURA (PF_VALOR, FC_IDFACTURA_FK, MP_IDMETODO_FK) VALUES (55000, @fc2, @mp_transf);

INSERT INTO KS_GASTOS (GS_CONCEPTO, GS_VALOR, GS_FECHA, SC_IDSUCURSAL_FK) 
VALUES ('Limpieza Insumos Sem 3', 35000, DATE_SUB(CURRENT_DATE(), INTERVAL 18 DAY), @sucursal_id);

INSERT INTO KS_SERVICIOS_TRABAJADOR (ST_VALOR_TOTAL, ST_NUMERO_CUOTAS, ST_VALOR_CUOTA, ST_ESTADO, ST_FECHA, ST_FECHA_INICIO_COBRO, TR_IDTRABAJADOR_FK)
VALUES (100000, 4, 25000, 'PENDIENTE', DATE_SUB(CURRENT_DATE(), INTERVAL 20 DAY), DATE_SUB(CURRENT_DATE(), INTERVAL 14 DAY), @juan_id);
SET @st1 = LAST_INSERT_ID();
INSERT INTO KS_SERVICIO_TRABAJADOR_CUOTAS (STC_NUMERO_CUOTA, STC_VALOR_CUOTA, STC_ESTADO, STC_FECHA_COBRO, ST_IDSERVICIO_TRABAJADOR_FK) VALUES 
(1, 25000, 'PAGADO', DATE_SUB(CURRENT_DATE(), INTERVAL 14 DAY), @st1),
(2, 25000, 'PENDIENTE', DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY), @st1),
(3, 25000, 'PENDIENTE', CURRENT_DATE(), @st1),
(4, 25000, 'PENDIENTE', DATE_ADD(CURRENT_DATE(), INTERVAL 7 DAY), @st1);

-- 5. SEMANA 2 (Hace 14 a 8 días)
INSERT INTO KS_FACTURAS (FC_NUMERO_FACTURA, FC_FECHA, FC_CLIENTE_NOMBRE, FC_CLIENTE_TELEFONO, FC_TOTAL, FC_ESTADO, SC_IDSUCURSAL_FK, TR_IDCAJERO_FK)
VALUES ('1003', DATE_SUB(CURRENT_DATE(), INTERVAL 12 DAY), 'Roberto Ruiz', '3125554433', 25000, 'PENDIENTE', @sucursal_id, @admin_id);
SET @fc3 = LAST_INSERT_ID();
INSERT INTO KS_FACTURA_DETALLES (FD_VALOR, FC_IDFACTURA_FK, SV_IDSERVICIO_FK, TR_IDTECNICO_FK) VALUES (25000, @fc3, @sv_corte, @pedro_id);
INSERT INTO KS_CREDITOS (CR_VALOR_PENDIENTE, CR_FECHA, FC_IDFACTURA_FK) VALUES (25000, DATE_SUB(CURRENT_DATE(), INTERVAL 12 DAY), @fc3);
SET @cr1 = LAST_INSERT_ID();
INSERT INTO KS_CREDITO_ABONOS (AB_VALOR, AB_FECHA, CR_IDCREDITO_FK) VALUES (10000, DATE_SUB(CURRENT_DATE(), INTERVAL 5 DAY), @cr1);

INSERT INTO KS_ADELANTOS (AD_MONTO, AD_OBSERVACIONES, AD_FECHA, AD_ESTADO, TR_IDTRABAJADOR_FK) 
VALUES (50000, 'Préstamo Maria Sem 2', DATE_SUB(CURRENT_DATE(), INTERVAL 10 DAY), 'PENDIENTE', @maria_id);

INSERT INTO KS_GASTOS (GS_CONCEPTO, GS_VALOR, GS_FECHA, SC_IDSUCURSAL_FK) 
VALUES ('Servicio Energía', 120000, DATE_SUB(CURRENT_DATE(), INTERVAL 9 DAY), @sucursal_id);

-- 6. SEMANA 1 (Hace 7 días a Hoy)
INSERT INTO KS_FACTURAS (FC_NUMERO_FACTURA, FC_FECHA, FC_CLIENTE_NOMBRE, FC_CLIENTE_TELEFONO, FC_TOTAL, FC_ESTADO, SC_IDSUCURSAL_FK, TR_IDCAJERO_FK)
VALUES ('1004', DATE_SUB(CURRENT_DATE(), INTERVAL 3 DAY), 'Grupo Amigos', '3138887766', 70000, 'PAGADO', @sucursal_id, @admin_id);
SET @fc4 = LAST_INSERT_ID();
INSERT INTO KS_FACTURA_DETALLES (FD_VALOR, FC_IDFACTURA_FK, SV_IDSERVICIO_FK, TR_IDTECNICO_FK) VALUES 
(25000, @fc4, @sv_corte, @juan_id), (25000, @fc4, @sv_corte, @maria_id), (20000, @fc4, @sv_barba, @pedro_id);
INSERT INTO KS_PAGOS_FACTURA (PF_VALOR, FC_IDFACTURA_FK, MP_IDMETODO_FK) VALUES (70000, @fc4, @mp_datafono);

INSERT INTO KS_GASTOS (GS_CONCEPTO, GS_VALOR, GS_FECHA, SC_IDSUCURSAL_FK) 
VALUES ('Transportes', 15000, DATE_SUB(CURRENT_DATE(), INTERVAL 2 DAY), @sucursal_id);

INSERT INTO KS_NOMINAS (NM_FECHA_INICIO, NM_FECHA_FIN, NM_TOTAL_PAGADO, NM_ESTADO, NM_FECHA_CIERRE)
VALUES (DATE_SUB(CURRENT_DATE(), INTERVAL 14 DAY), DATE_SUB(CURRENT_DATE(), INTERVAL 8 DAY), 450000, 'CERRADA', DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY));
SET @nm1 = LAST_INSERT_ID();
INSERT INTO KS_NOMINA_DETALLES (ND_BASE, ND_COMISIONES, ND_BONOS, ND_DEDUCCIONES_SERVICIOS_TRABAJADOR, ND_TOTAL_NETO, NM_IDNOMINA_FK, TR_IDTRABAJADOR_FK)
VALUES (100000, 50000, 10000, 25000, 135000, @nm1, @juan_id);

-- 7. DÍA ACTUAL (Hoy)
INSERT INTO KS_FACTURAS (FC_NUMERO_FACTURA, FC_FECHA, FC_CLIENTE_NOMBRE, FC_CLIENTE_TELEFONO, FC_TOTAL, FC_ESTADO, SC_IDSUCURSAL_FK, TR_IDCAJERO_FK)
VALUES ('2001', CURRENT_DATE(), 'Cliente Hoy 1', '3141112233', 25000, 'PAGADO', @sucursal_id, @admin_id);
SET @fc5 = LAST_INSERT_ID();
INSERT INTO KS_FACTURA_DETALLES (FD_VALOR, FC_IDFACTURA_FK, SV_IDSERVICIO_FK, TR_IDTECNICO_FK) VALUES (25000, @fc5, @sv_corte, @pedro_id);
INSERT INTO KS_PAGOS_FACTURA (PF_VALOR, FC_IDFACTURA_FK, MP_IDMETODO_FK) VALUES (25000, @fc5, @mp_efectivo);

INSERT INTO KS_FACTURAS (FC_NUMERO_FACTURA, FC_FECHA, FC_CLIENTE_NOMBRE, FC_CLIENTE_TELEFONO, FC_TOTAL, FC_ESTADO, SC_IDSUCURSAL_FK, TR_IDCAJERO_FK)
VALUES ('2002', CURRENT_DATE(), 'Cliente Hoy 2', '3144445566', 45000, 'PAGADO', @sucursal_id, @admin_id);
SET @fc6 = LAST_INSERT_ID();
INSERT INTO KS_FACTURA_DETALLES (FD_VALOR, FC_IDFACTURA_FK, SV_IDSERVICIO_FK, TR_IDTECNICO_FK) VALUES (15000, @fc6, @sv_barba, @juan_id);
INSERT INTO KS_FACTURA_PRODUCTOS (FP_VALOR, FC_IDFACTURA_FK, PR_IDPRODUCTO_FK, TR_IDTECNICO_FK) VALUES (30000, @fc6, @pr_cera, @juan_id);
INSERT INTO KS_PAGOS_FACTURA (PF_VALOR, FC_IDFACTURA_FK, MP_IDMETODO_FK) VALUES (45000, @fc6, @mp_datafono);

INSERT INTO KS_GASTOS (GS_CONCEPTO, GS_VALOR, GS_FECHA, SC_IDSUCURSAL_FK) 
VALUES ('Gasto Misceláneo Hoy', 12000, CURRENT_DATE(), @sucursal_id);
